---
- name: Install web server
  hosts: all
  become_user: root
  become_method: sudo
  become: yes 

  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: latest
  - name: Run apache
    ansible.builtin.service:
      name: httpd
      state: started
